from __future__ import annotations

from enum import Enum


class Severity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"


class MoveType(str, Enum):
    SWAP_ORDER_ON_MACHINE = "SWAP_ORDER_ON_MACHINE"
    MOVE_TO_ALTERNATE_MACHINE = "MOVE_TO_ALTERNATE_MACHINE"
    SHIFT_TO_FILL_IDLE_WINDOW = "SHIFT_TO_FILL_IDLE_WINDOW"
    PULL_FORWARD_CRITICAL_OP = "PULL_FORWARD_CRITICAL_OP"
    BATCH_SAME_SETUP_FAMILY = "BATCH_SAME_SETUP_FAMILY"
    INCREASE_OT_OR_ADD_SHIFT = "INCREASE_OT_OR_ADD_SHIFT"
    HIRE_OUTSOURCE_LABOR = "HIRE_OUTSOURCE_LABOR"
    REQUEST_DUE_DATE_EXTENSION = "REQUEST_DUE_DATE_EXTENSION"


class ResourceMode(str, Enum):
    MACHINE = "machine"
    LABOR = "labor"
